create database student10;
use student10;
create table details(id int,name varchar(30),address varchar(20),mathematics int,physics int,computer_science int,total_mark int);
insert into details value(321,"varun","paruvayal",150,150,150,450);
insert into details value(322,"sarang","koduvally",149,139,109,397);
insert into details value(323,"reema","kozhikode",190,198,98,486);
insert into details value(324,"adwaith","mavoor",100,101,110,311);
select * from details;
update details set total_mark=250 where name="varun";
select * from details;
select total_mark,name from details where name="reema" and total_mark  is not null;
update details set name="robin zachariah" where name="adwaith";
select * from details;
select * from details where address = 'kozhikode' or address = 'mavoor';
alter table details add department varchar(25);
update  details set department="MCA" WHERE name ="varun";
update  details set department="EEE" WHERE name ="reema";
select name from details order by name desc;
insert into details value(329,"adwaith","mavoor",100,101,110,311,null);
insert into details value(334,"asheeka",null,100,101,10,11,null);
select  name from details  where address is null;
select max(total_mark) from details;
select min(mathematics) from details;
select sum(mathematics) from details;
select sum(mathematics)/3 from details;
select department from details where department like "%E";
SELECT NAME FROM DETAILS WHERE NAME LIKE "A%";
ALTER TABLE DETAILS DROP TOTAL_MARK;
ALTER TABLE DETAILS ADD TOTALMARK INT;
update  details set TOTALMARK=mathematics+physics+computer_science WHERE name ="varun";
update  details set TOTALMARK=mathematics+physics+computer_science WHERE name ="reema";
update  details set TOTALMARK=mathematics+physics+computer_science WHERE name ="robin zachariah";
update  details set TOTALMARK=mathematics+physics+computer_science WHERE name ="adwaith";
update  details set TOTALMARK=mathematics+physics+computer_science WHERE name ="asheeka";
ALTER TABLE DETAILS ADD Age INT;
update  details set age=20 WHERE name ="varun";
update  details set age=21 WHERE name ="reema";
update  details set age=23 WHERE name ="robin zachariah";
update  details set age=20 WHERE name ="adwaith";
update  details set age=21 WHERE name ="asheeka";
alter table details add constraint test1 check(total_mark>400);
ALTER TABLE DETAILS drop check test1;
create view  topper as select name from details where age=21;
select * from topper;
drop view topper;
delete  from details where age =23;
commit;
delete  from details where name="adwaith";
update  details set age=25 WHERE name ="varun";
rollback;
ALTER TABLE DETAILS ADD id INT;
update  details set id=1 WHERE name ="varun";
update  details set id=2 WHERE name ="reema";
update  details set id=3 WHERE name ="asheeka";
update  details set age=20 WHERE id=1;
savepoint save;
rollback to save;
